language: python
os: linux
dist: focal
python:
  - "3.7"

notifications:
  email: false

addons:
  apt:
    update: true
    packages: 
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-science
      - texlive-xetex
      - latexmk
      - fonts-freefont-otf

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.7"

install: 
   - source travis-ci/travis_install.sh
   - source travis-ci/travis_conda.sh

script:
   - for f in `ls building/build*.sh`; do source $f; done

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
   keep_history: true
   file: "lectures/BimodalImaging/_build/latex/Kaestner-BimodalExperiments.pdf"
   target_branch: gh-pages
   on:
     branch: main
