# Book settings
title: Bimodal experiments
only_build_toc_files: true

author: Anders Kaestner
#logo: 'images/logo.png'

execute:
  timeout: -1
  execute_notebooks: auto

latex:
  latex_documents:
     targetname: Kaestner_BimodalExperiments.tex
